### ISSUE TITLE
Ipad mini IOS9 dragging between connected trees

### ISSUE THREAD

**Issue by StuartRayson** [angular-ui-tree/angular-ui-tree#621]
Looking to start a new angular project with drag and drop. 

This looks perfect but recently trying your demo on the ipad ios9 i can't drag between connected trees or re order nodes on the demo.

**Comment by StefanCodes** [comment]
That was fixed in https://github.com/angular-ui-tree/angular-ui-tree/pull/554 but it looks like those changes aren't deployed to the demo site yet.
I'll have a look later and see if I can figure out how to update it.

In the meantime, @StuartRayson, you could copy the connected trees demo page and replace the script references with the latest build of angular-ui-tree and it ought to work for you (or at least work better than it does right now).

**Comment by StefanCodes** [comment]
@StuartRayson the demo site looks up to date with 2.9.0 now - can you give it another try?

**Comment by StuartRayson** [comment]
Thanks @StefanCodes looks to be working now.

I'm having issues with my own solution works fine on IOS8 but not 9, even though I'm using version 2.9.0 =/. I'll just compare against the new example. 

Thanks again

**Comment by StuartRayson** [comment]
Hey @StefanCodes,
I've retested on the device I originally found the issue on and I'm still have the issue, seems like an odd one. it works on fine on ipad mini 1 but not on ipad mini 2. =S

**Comment by SvenJunga** [comment]
@StuartRayson: is the latter device running iOS 8.4.1? Just in case, can you try updating to iOS >= 9.0.0?

**Comment by StuartRayson** [comment]
@SvenJunga both are updated to ios9

**Comment by StuartRayson** [comment]
@StefanCodes @SvenJunga... so it was a ios issue. =/
Version 9.0.2 has resolved it with the improvements to touch.   

Headache over
